### ISSUE TITLE
Meetup Events not updating

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/upstate_tech_cal_service#15] opened 2019-06-25 22:40 UTC
Why: A user would be confused if they see an event on the calendar which was canceled because it still shows on our event calendar.

What: Presently when an event is canceled after it was scheduled, it is not updated and continues to display. 

Determine where in the API the issue exists.

Example: This event which is showing in the [api](https://greenville-cal-service.herokuapp.com/api/gtc) has been deleted and is not returning on `https://secure.meetup.com/meetup_api/console/?path=/2/events`
`{
    "created_at": "2017-07-31T03:56:47Z", 
    "data_as_of": "2019-01-27T05:43:14Z", 
    "description": "Bring your laptop and join us for our monthly Hack Night\u00a0- drop-ins welcome! You are invited to work on any coding project you have, learn to code while enjoying a hacking atmosphere and network with other women developers. You will have the opportunity to announce your project or ask for help and mingle with other women in tech. If you're just starting off with coding, come, and we'll help you choose tutorials and learn further.\u00a0Some of our members are working on\u00a0<a href=\"https://www.freecodecamp.com/\">freeCodeCamp</a>. Just checking out what everyone else is doing is OK, too! If you have skills to\u00a0share, please come to help mentor and answer questions. THANKS to our host <a href=\"https://joinopenworks.com/\">OpenWorks</a>! <b>Schedule:</b> 6:00pm Arrive/Network/Food<br/>6:30pm Welcome &amp; Announcements<br/>6:45pm Freestyle Hack Night", 
    "event_name": "WWCode Hack Night", 
    "group_name": "Women Who Code Greenville", 
    "nid": "40", 
    "rsvp_count": 1, 
    "tags": "1", 
    "time": "2019-07-04T22:00:00Z", 
    "url": "https://www.meetup.com/Women-Who-Code-Greenville/events/mvgpnnyzkbgb/", 
    "uuid": "788992ce-51f8-44e2-b300-d495303e0025", 
    "venue": null
  }, `

**Comment by jeremywight** [comment] 2019-06-25 22:41
We are looking at the meetup.com event api and it is returning the proper response here: https://secure.meetup.com/meetup_api/console/?path=/2/events

**Comment by jeremywight** [comment] 2019-06-25 23:30
@Nunie123 could you write us instructions for running this locally? We think we can get it debugged if we can get it running locally, but we're running into questions. I'm wondering if the update file https://github.com/codeforgreenville/upstate_tech_cal_service/blob/825cecea83d9866d1999f003b8b475f074e74c61/update_cal_data.py#L20 isn't being referenced when an update occurs, or if there are any error logs on this cc @MarkMcDaniels

**Comment by allella** [comment] 2019-06-28 01:12
@jeremywight here is the [documentation we have for how this is working](https://github.com/codeforgreenville/upstate_tech_cal_service/issues/14).

We'll want to move or figure a different hosting situation but we previously picked Ed's brain and took those notes.

My question on this issue is if the problem is that Meetup is changing the status but not removing the record and that this script is not looking at the status.  I ask because I believe this script (Ed's) is downloading the events every time it runs and doesn't have a database behind it. So, if a cancelled event is persisting I'm wondering if it's because Meetup.com's API is still returning it but this script is not considering the event's status, and so it continues to show a cancelled event.

**Comment by allella** [comment] 2019-06-28 01:20
For instance, if we go to the Meetup events API
https://secure.meetup.com/meetup_api/console/?path=/2/events
and enter "Women-Who-Code-Greenville" into the "group_urlname" field it returns 11 events all with a status of "upcoming".

Is the cancelled event not showing in Meetup.com's API, or is it still showing as "upcoming" even though it's not longer valid?

**Comment by MarkMcDaniels** [comment] 2019-06-28 02:12
@allella and @jeremywight. The events api has a status attribute in the request that could be used to test against.

if the event.status is not cancelled
        add it to the list
otherwise keep on moving

I'll at least take a look, and try to find it.

**Comment by allella** [comment] 2019-07-02 16:34
Alright, so I was thinking this was due to Meetup still rendering the event in its API and this script not being smart enough to ignore a bad status. However, the July 2 event was cancelled and it is NOT showing in https://secure.meetup.com/meetup_api/console/?path=/2/events
when groupurl_name = "Code-For-Greenville" so the issue would appear to be on this end.

**Comment by allella** [comment] 2019-08-13 23:33
Okay, so what @MarkMcDaniels suggested with the "status" parameter in the v2 API is probably the reason cancelled events don't show.  It defaults to "upcoming". 

@MarkMcDaniels  @bcsnipes including you so you can `git pull origin master` to get the latest changes.

This means "past" events also roll off, which may or may not be desirable.

This repo is using the [now deprecated Meetup v2 API](https://www.meetup.com/meetup_api/docs/2/events/).

Here's a [list of upcoming AND cancelled AND past](https://api.meetup.com/2/events?key=INSERT_YOUR_MEETUP_COM_DEVELOPER_API_KEY_HERE_FOR_THIS_TO_WORK&group_id=20727833,3858912,14215742,238427597,29623789,18938823,19350568,1677620,18709783,18394107,25719159,25648732,3523622,25827186,18320881,29424521,20317900,16270362,10755802,14034232&limited_events=true&status=upcoming,cancelled
), which is specified using the `&status=upcoming,cancelled` parameter

ALSO, this API endpoint has a parameter called **&limited_events** and it defaults to "false".

This was preventing the Data Analytics group from showing in our API because that group is semi-public, so adding _&limited_events=true_ to the API call fixed that issue.

This may have fixed two issues, but now we also have some duplication, which may be related to having two groups posting under the same Meetup.com account.

Also, note the Eventbrite API has a [2000/requests per hour rate limit](https://www.eventbrite.com/platform/docs/rate-limits) and it probably makes hundreds of requests per execution, so if you're debugging you may run into its rate limit rather quickly.

Eventbrite /events docs
https://www.eventbrite.com/platform/api#/reference/event

**Comment by allella** [comment] 2019-08-13 23:37
This commit message highlights workarounds and things I had to do to get the darn thing to work. I intend to clean these up.

https://github.com/codeforgreenville/upstate_tech_cal_service/commit/0d37a9109f11de547a3cb98055373d559d0ab9e6

**Comment by allella** [comment] 2019-08-14 18:14
@pamelawoodbrowne including you since you noticed the changes and the new duplicate issue.

We may also start to see cancelled events on the calendars, but I have a new issue for that and we'll be adding a status field to allow consuming apps to distinguish cancelled from upcoming, etc.

Closing this issue, since the missing items were likely due to the semi-private settings selected by the meetup.  The &limited_events=true mentioned above should have fixed that, since it did for the Data Analytics group.

https://github.com/codeforgreenville/upstate_tech_cal_service/issues/18
https://github.com/codeforgreenville/upstate_tech_cal_service/issues/16
https://github.com/codeforgreenville/upstate_tech_cal_service/issues/17

**Closed as completed by allella** 2019-08-14 18:14 UTC
